### ISSUE TITLE
Data file damaged?

### ISSUE THREAD

**Issue by ryan-224** [ngminhtri0394/GEFA#2]
Hi there,

I cloned this repo and would like to test the model.
However, the data.tar.gz seems like damaged as it is just a text file and cannot be unzipped.
![image](https://user-images.githubusercontent.com/58620549/112110241-96e48200-8bed-11eb-8083-93717cf8002e.png)
Could you please take a look?

Thank you.

**Comment by ngminhtri0394** [comment]
Hello,

Your problem is similar to this one https://stackoverflow.com/questions/60172926/git-checkout-getting-ascii-file-instead-of-binary.

The data file is uploaded via Git LFS.  The file you try to unzipped is just a pointer. You need to install Git LFS to download large file.

**Comment by ryan-224** [comment]
Thanks for your help :)
That solved my problem.
