### ISSUE TITLE
Contact map and secondary structure prediction

### ISSUE THREAD

**Issue by ryan-224** [ngminhtri0394/GEFA#3]
Hi there,

In the paper, you mentioned the contact map was predicted by RaptorX.

I tried to re-produce the contact map, ss8 and acc files with the latest version of RaptorX. But the results were different from your data/profile files.

May I know more about/Could you please release the code to produce those files?

Many thanks.

**Comment by ngminhtri0394** [comment]
Hello,

The contact maps were from the webservice. We ran it long time ago so I'm not sure they were the latest version. The ss8 and acc is from this repo https://github.com/realbigws/Predict_Property.

**Comment by ryan-224** [comment]
Thanks, will try it out.
